db:
  image: mariadb:10.1
  environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_USER=joomla
    - MYSQL_PASSWORD=joomla
    - MYSQL_DATABASE=joomla
web:
  image: seterrychen/joomla-without-database:3.5.0
  links:
    - db:mariadb
  ports:
    - "10082:80"
  environment:
    - JOOMLA_DB_HOST=db_1
    - JOOMLA_DB_USER=joomla
    - JOOMLA_DB_PASSWORD=joomla
    - JOOMLA_DB_NAME=joomla
